sudo: required
services:
  - docker

before_install:
  - docker build -t krajem/multi-test -f ./client/Dockerfile.dev ./client

script:
  - docker run krajem/multi-test npm test -- --coverage

after_success:
  - docker build -t krajem/multi-client ./client
  - docker build -t krajem/multi-nginx ./nginx
  - docker build -t krajem/multi-server ./server
  - docker build -t krajem/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push krajem/multi-client
  - docker push krajem/multi-nginx
  - docker push krajem/multi-server
  - docker push krajem/multi-worker

deploy:
  provider: elasticbeanstalk
  region: eu-west-2
  app: docker-react-test 
  env: DockerReactTest-environment
  bucket_name: elasticbeanstalk-eu-west-2-747499340633
  bucket_path: docker-react-test
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
